/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module \$paramod\uart_rx\CLKS_PER_BIT=s32'00000000000000000000000011011001 (clk, rx, rx_valid, rx_data);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire [7:0] baud_cnt;
  wire [2:0] bit_cnt;
  input clk;
  wire clk;
  input rx;
  wire rx;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  wire [7:0] rx_shift_reg;
  output rx_valid;
  wire rx_valid;
  wire rx_valid_reg;
  wire [2:0] state;
  sky130_fd_sc_hd__clkinv_1 _089_ (
    .A(baud_cnt[4]),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _090_ (
    .A(baud_cnt[7]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _091_ (
    .A(state[1]),
    .SLEEP(state[2]),
    .X(_052_)
  );
  sky130_fd_sc_hd__or3b_1 _092_ (
    .A(state[0]),
    .B(state[2]),
    .C_N(state[1]),
    .X(_053_)
  );
  sky130_fd_sc_hd__a21oi_1 _093_ (
    .A1(baud_cnt[3]),
    .A2(baud_cnt[4]),
    .B1(baud_cnt[5]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _094_ (
    .A(baud_cnt[6]),
    .B(baud_cnt[7]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _095_ (
    .A(_054_),
    .SLEEP(_055_),
    .X(_056_)
  );
  sky130_fd_sc_hd__nor3_1 _096_ (
    .A(_053_),
    .B(_054_),
    .C(_055_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__or3_1 _097_ (
    .A(_053_),
    .B(_054_),
    .C(_055_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _098_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor4_1 _099_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .D(_058_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(rx_shift_reg[0]),
    .A1(rx),
    .S(_060_),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2b_1 _101_ (
    .A_N(bit_cnt[1]),
    .B(bit_cnt[0]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xor2_1 _102_ (
    .A(bit_cnt[2]),
    .B(_059_),
    .X(_062_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _103_ (
    .A(_058_),
    .SLEEP(_062_),
    .X(_063_)
  );
  sky130_fd_sc_hd__o21ai_0 _104_ (
    .A1(_061_),
    .A2(_063_),
    .B1(rx_shift_reg[1]),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nand2b_1 _105_ (
    .A_N(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _106_ (
    .A(_061_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand3_1 _107_ (
    .A(bit_cnt[0]),
    .B(rx),
    .C(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__o21ai_0 _108_ (
    .A1(_063_),
    .A2(_067_),
    .B1(_064_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21ai_0 _109_ (
    .A1(_063_),
    .A2(_065_),
    .B1(rx_shift_reg[2]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nand3b_1 _110_ (
    .A_N(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(rx),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(_063_),
    .A2(_069_),
    .B1(_068_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nand2_1 _112_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__or3_1 _113_ (
    .A(_058_),
    .B(_062_),
    .C(_070_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(rx_shift_reg[3]),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand3_1 _115_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(rx),
    .Y(_073_)
  );
  sky130_fd_sc_hd__o21ai_0 _116_ (
    .A1(_063_),
    .A2(_073_),
    .B1(_072_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand3_1 _117_ (
    .A(bit_cnt[2]),
    .B(_057_),
    .C(_059_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor4bb_1 _118_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C_N(bit_cnt[2]),
    .D_N(rx),
    .Y(_075_)
  );
  sky130_fd_sc_hd__a22o_1 _119_ (
    .A1(rx_shift_reg[4]),
    .A2(_074_),
    .B1(_075_),
    .B2(_057_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _120_ (
    .A(_057_),
    .B(_062_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__o21ai_0 _121_ (
    .A1(_061_),
    .A2(_076_),
    .B1(rx_shift_reg[5]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__o21ai_0 _122_ (
    .A1(_067_),
    .A2(_076_),
    .B1(_077_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__o21ai_0 _123_ (
    .A1(_065_),
    .A2(_076_),
    .B1(rx_shift_reg[6]),
    .Y(_078_)
  );
  sky130_fd_sc_hd__o21ai_0 _124_ (
    .A1(_069_),
    .A2(_076_),
    .B1(_078_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o21ai_0 _125_ (
    .A1(_070_),
    .A2(_076_),
    .B1(rx_shift_reg[7]),
    .Y(_079_)
  );
  sky130_fd_sc_hd__o21ai_0 _126_ (
    .A1(_073_),
    .A2(_076_),
    .B1(_079_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _127_ (
    .A(state[0]),
    .B(_052_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(_056_),
    .B(_080_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o21ai_0 _129_ (
    .A1(state[1]),
    .A2(state[0]),
    .B1(rx_valid_reg),
    .Y(_081_)
  );
  sky130_fd_sc_hd__o21ai_0 _130_ (
    .A1(_056_),
    .A2(_080_),
    .B1(_081_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor3_1 _131_ (
    .A(state[1]),
    .B(state[0]),
    .C(state[2]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _132_ (
    .A(_057_),
    .B(_082_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _133_ (
    .A(bit_cnt[0]),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__o21ai_0 _134_ (
    .A1(bit_cnt[0]),
    .A2(_058_),
    .B1(_084_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a22o_1 _135_ (
    .A1(_057_),
    .A2(_066_),
    .B1(_083_),
    .B2(bit_cnt[1]),
    .X(_010_)
  );
  sky130_fd_sc_hd__a21oi_1 _136_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .B1(_058_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _137_ (
    .A1(_083_),
    .A2(_085_),
    .B1(bit_cnt[2]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nand2_1 _138_ (
    .A(_071_),
    .B(_086_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand4bb_1 _139_ (
    .A_N(baud_cnt[0]),
    .B_N(baud_cnt[1]),
    .C(baud_cnt[2]),
    .D(baud_cnt[3]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand2_1 _140_ (
    .A(baud_cnt[5]),
    .B(baud_cnt[6]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor4_1 _141_ (
    .A(baud_cnt[4]),
    .B(baud_cnt[7]),
    .C(_087_),
    .D(_088_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor3b_1 _142_ (
    .A(state[1]),
    .B(state[2]),
    .C_N(state[0]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _143_ (
    .A(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a31o_1 _144_ (
    .A1(rx),
    .A2(_023_),
    .A3(_024_),
    .B1(state[2]),
    .X(_026_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _145_ (
    .A(_023_),
    .SLEEP(_025_),
    .X(_027_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _146_ (
    .A1_N(_052_),
    .A2_N(_056_),
    .B1(_023_),
    .B2(_025_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(_028_),
    .A1(_026_),
    .S(baud_cnt[0]),
    .X(_012_)
  );
  sky130_fd_sc_hd__a21o_1 _148_ (
    .A1(_052_),
    .A2(_056_),
    .B1(_024_),
    .X(_029_)
  );
  sky130_fd_sc_hd__xor2_1 _149_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .X(_030_)
  );
  sky130_fd_sc_hd__a22o_1 _150_ (
    .A1(baud_cnt[1]),
    .A2(_026_),
    .B1(_029_),
    .B2(_030_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand3_1 _151_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .C(baud_cnt[2]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _152_ (
    .A1(_028_),
    .A2(_031_),
    .B1(_026_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a31oi_1 _153_ (
    .A1(baud_cnt[0]),
    .A2(baud_cnt[1]),
    .A3(_028_),
    .B1(baud_cnt[2]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor2_1 _154_ (
    .A(_032_),
    .B(_033_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a41oi_1 _155_ (
    .A1(baud_cnt[0]),
    .A2(baud_cnt[1]),
    .A3(baud_cnt[2]),
    .A4(_028_),
    .B1(baud_cnt[3]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a21oi_1 _156_ (
    .A1(baud_cnt[3]),
    .A2(_032_),
    .B1(_034_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand4_1 _157_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .C(baud_cnt[2]),
    .D(baud_cnt[3]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(_050_),
    .B(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _159_ (
    .A(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a22oi_1 _160_ (
    .A1(baud_cnt[4]),
    .A2(state[2]),
    .B1(_029_),
    .B2(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _161_ (
    .A1(_050_),
    .A2(_035_),
    .B1(_038_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(baud_cnt[5]),
    .B(_036_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _163_ (
    .A(baud_cnt[5]),
    .B(_036_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a22oi_1 _164_ (
    .A1(baud_cnt[5]),
    .A2(_026_),
    .B1(_028_),
    .B2(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nor2_1 _165_ (
    .A(_039_),
    .B(_041_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__a21oi_1 _166_ (
    .A1(baud_cnt[5]),
    .A2(_036_),
    .B1(baud_cnt[6]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _167_ (
    .A(baud_cnt[5]),
    .B(baud_cnt[6]),
    .C(_036_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a22oi_1 _168_ (
    .A1(baud_cnt[6]),
    .A2(_026_),
    .B1(_028_),
    .B2(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor2_1 _169_ (
    .A(_042_),
    .B(_044_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _170_ (
    .A1(_029_),
    .A2(_043_),
    .B1(_026_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _171_ (
    .A(_051_),
    .B(_029_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o22ai_1 _172_ (
    .A1(_051_),
    .A2(_045_),
    .B1(_046_),
    .B2(_043_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand3_1 _173_ (
    .A(state[0]),
    .B(_052_),
    .C(_056_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2b_1 _174_ (
    .A_N(rx),
    .B(_082_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__o2111ai_1 _175_ (
    .A1(_070_),
    .A2(_076_),
    .B1(_027_),
    .C1(_047_),
    .D1(_048_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand3b_1 _176_ (
    .A_N(rx),
    .B(_023_),
    .C(_024_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand3_1 _177_ (
    .A(_053_),
    .B(_047_),
    .C(_049_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__dfxtp_1 _178_ (
    .CLK(clk),
    .D(_000_),
    .Q(rx_shift_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _179_ (
    .CLK(clk),
    .D(_001_),
    .Q(rx_shift_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _180_ (
    .CLK(clk),
    .D(_002_),
    .Q(rx_shift_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _181_ (
    .CLK(clk),
    .D(_003_),
    .Q(rx_shift_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _182_ (
    .CLK(clk),
    .D(_004_),
    .Q(rx_shift_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _183_ (
    .CLK(clk),
    .D(_005_),
    .Q(rx_shift_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _184_ (
    .CLK(clk),
    .D(_006_),
    .Q(rx_shift_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _185_ (
    .CLK(clk),
    .D(_007_),
    .Q(rx_shift_reg[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _186_ (
    .CLK(clk),
    .D(_008_),
    .Q(rx_valid_reg)
  );
  sky130_fd_sc_hd__dfxtp_1 _187_ (
    .CLK(clk),
    .D(_009_),
    .Q(bit_cnt[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _188_ (
    .CLK(clk),
    .D(_010_),
    .Q(bit_cnt[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _189_ (
    .CLK(clk),
    .D(_011_),
    .Q(bit_cnt[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _190_ (
    .CLK(clk),
    .D(_012_),
    .Q(baud_cnt[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _191_ (
    .CLK(clk),
    .D(_013_),
    .Q(baud_cnt[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _192_ (
    .CLK(clk),
    .D(_014_),
    .Q(baud_cnt[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _193_ (
    .CLK(clk),
    .D(_015_),
    .Q(baud_cnt[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _194_ (
    .CLK(clk),
    .D(_016_),
    .Q(baud_cnt[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _195_ (
    .CLK(clk),
    .D(_017_),
    .Q(baud_cnt[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _196_ (
    .CLK(clk),
    .D(_018_),
    .Q(baud_cnt[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _197_ (
    .CLK(clk),
    .D(_019_),
    .Q(baud_cnt[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _198_ (
    .CLK(clk),
    .D(_020_),
    .Q(state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _199_ (
    .CLK(clk),
    .D(_021_),
    .Q(state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _200_ (
    .CLK(clk),
    .D(_022_),
    .Q(state[2])
  );
  assign rx_data = rx_shift_reg;
  assign rx_valid = rx_valid_reg;
endmodule

module \$paramod\uart_tx\CLKS_PER_BIT=s32'00000000000000000000000011011001 (clk, tx_start, tx_data, tx, tx_done);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire [7:0] baud_cnt;
  wire [2:0] bit_cnt;
  input clk;
  wire clk;
  wire [2:0] state;
  output tx;
  wire tx;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output tx_done;
  wire tx_done;
  wire tx_done_reg;
  wire tx_reg;
  wire [7:0] tx_shift_reg;
  input tx_start;
  wire tx_start;
  sky130_fd_sc_hd__clkinv_1 _074_ (
    .A(baud_cnt[3]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _075_ (
    .A(state[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3b_1 _076_ (
    .A_N(state[2]),
    .B(state[1]),
    .C(state[0]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__a21o_1 _077_ (
    .A1(baud_cnt[3]),
    .A2(baud_cnt[4]),
    .B1(baud_cnt[5]),
    .X(_044_)
  );
  sky130_fd_sc_hd__and2_0 _078_ (
    .A(baud_cnt[6]),
    .B(baud_cnt[7]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nand2_1 _079_ (
    .A(_044_),
    .B(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _080_ (
    .A(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _081_ (
    .A(_043_),
    .B(_046_),
    .Y(_000_)
  );
  sky130_fd_sc_hd__or4_1 _082_ (
    .A(state[2]),
    .B(state[1]),
    .C(_042_),
    .D(_046_),
    .X(_048_)
  );
  sky130_fd_sc_hd__nor3b_1 _083_ (
    .A(state[2]),
    .B(state[0]),
    .C_N(state[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand3b_1 _084_ (
    .A_N(state[2]),
    .B(state[1]),
    .C(_042_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__o211ai_1 _085_ (
    .A1(_043_),
    .A2(_047_),
    .B1(_048_),
    .C1(_050_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nand2_1 _086_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand3_1 _087_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[2]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and3_1 _088_ (
    .A(_044_),
    .B(_045_),
    .C(_049_),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand2b_1 _089_ (
    .A_N(_052_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _090_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor3_1 _091_ (
    .A(state[2]),
    .B(state[1]),
    .C(state[0]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nand2_1 _092_ (
    .A(tx_start),
    .B(_056_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__o311ai_0 _093_ (
    .A1(state[2]),
    .A2(_042_),
    .A3(_047_),
    .B1(_054_),
    .C1(_057_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__o21ai_0 _094_ (
    .A1(state[1]),
    .A2(state[0]),
    .B1(tx_done_reg),
    .Y(_058_)
  );
  sky130_fd_sc_hd__o21ai_0 _095_ (
    .A1(_043_),
    .A2(_046_),
    .B1(_058_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__a31oi_1 _096_ (
    .A1(_044_),
    .A2(_045_),
    .A3(_049_),
    .B1(_056_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(_053_),
    .A1(_059_),
    .S(bit_cnt[0]),
    .X(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _098_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__a22oi_1 _099_ (
    .A1(_051_),
    .A2(_053_),
    .B1(_059_),
    .B2(bit_cnt[1]),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _100_ (
    .A(_060_),
    .B(_061_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__a21oi_1 _101_ (
    .A1(bit_cnt[0]),
    .A2(bit_cnt[1]),
    .B1(bit_cnt[2]),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a22oi_1 _102_ (
    .A1(_052_),
    .A2(_053_),
    .B1(_059_),
    .B2(bit_cnt[2]),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(_062_),
    .B(_063_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__mux4_2 _104_ (
    .A0(tx_shift_reg[4]),
    .A1(tx_shift_reg[5]),
    .A2(tx_shift_reg[6]),
    .A3(tx_shift_reg[7]),
    .S0(bit_cnt[0]),
    .S1(bit_cnt[1]),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux4_2 _105_ (
    .A0(tx_shift_reg[0]),
    .A1(tx_shift_reg[1]),
    .A2(tx_shift_reg[2]),
    .A3(tx_shift_reg[3]),
    .S0(bit_cnt[0]),
    .S1(bit_cnt[1]),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2i_1 _106_ (
    .A0(_065_),
    .A1(_064_),
    .S(bit_cnt[2]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nand2_1 _107_ (
    .A(tx_reg),
    .B(state[2]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _108_ (
    .A(_043_),
    .B(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_056_),
    .B(_068_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__o21ai_0 _110_ (
    .A1(_050_),
    .A2(_066_),
    .B1(_069_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__a211oi_1 _111_ (
    .A1(_044_),
    .A2(_045_),
    .B1(_055_),
    .C1(state[2]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(_070_),
    .A1(state[2]),
    .S(baud_cnt[0]),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _113_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__a22oi_1 _115_ (
    .A1(baud_cnt[1]),
    .A2(state[2]),
    .B1(_070_),
    .B2(_072_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _116_ (
    .A(_071_),
    .B(_073_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _117_ (
    .A1(baud_cnt[0]),
    .A2(baud_cnt[1]),
    .B1(baud_cnt[2]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand3_1 _118_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .C(baud_cnt[2]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__a22oi_1 _119_ (
    .A1(baud_cnt[2]),
    .A2(state[2]),
    .B1(_070_),
    .B2(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _120_ (
    .A(_024_),
    .B(_026_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__and4_1 _121_ (
    .A(baud_cnt[0]),
    .B(baud_cnt[1]),
    .C(baud_cnt[2]),
    .D(baud_cnt[3]),
    .X(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _122_ (
    .A(_027_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a22oi_1 _123_ (
    .A1(baud_cnt[3]),
    .A2(state[2]),
    .B1(_070_),
    .B2(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _124_ (
    .A1(_041_),
    .A2(_025_),
    .B1(_029_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _125_ (
    .A(baud_cnt[4]),
    .B(_027_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _126_ (
    .A(baud_cnt[4]),
    .B(_027_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a22oi_1 _127_ (
    .A1(baud_cnt[4]),
    .A2(state[2]),
    .B1(_070_),
    .B2(_031_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _128_ (
    .A(_030_),
    .B(_032_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21oi_1 _129_ (
    .A1(baud_cnt[4]),
    .A2(_027_),
    .B1(baud_cnt[5]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__and3_1 _130_ (
    .A(baud_cnt[4]),
    .B(baud_cnt[5]),
    .C(_027_),
    .X(_034_)
  );
  sky130_fd_sc_hd__nand3_1 _131_ (
    .A(baud_cnt[4]),
    .B(baud_cnt[5]),
    .C(_027_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a22oi_1 _132_ (
    .A1(baud_cnt[5]),
    .A2(state[2]),
    .B1(_070_),
    .B2(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _133_ (
    .A(_033_),
    .B(_036_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand4_1 _134_ (
    .A(baud_cnt[4]),
    .B(baud_cnt[5]),
    .C(baud_cnt[6]),
    .D(_027_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__a21oi_1 _135_ (
    .A1(_070_),
    .A2(_037_),
    .B1(state[2]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _136_ (
    .A1(_070_),
    .A2(_034_),
    .B1(baud_cnt[6]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(_038_),
    .B(_039_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a31oi_1 _138_ (
    .A1(baud_cnt[6]),
    .A2(_070_),
    .A3(_034_),
    .B1(baud_cnt[7]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _139_ (
    .A1(baud_cnt[7]),
    .A2(_038_),
    .B1(_040_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _140_ (
    .A0(tx_data[0]),
    .A1(tx_shift_reg[0]),
    .S(_057_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(tx_data[1]),
    .A1(tx_shift_reg[1]),
    .S(_057_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _142_ (
    .A0(tx_data[2]),
    .A1(tx_shift_reg[2]),
    .S(_057_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _143_ (
    .A0(tx_data[3]),
    .A1(tx_shift_reg[3]),
    .S(_057_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(tx_data[4]),
    .A1(tx_shift_reg[4]),
    .S(_057_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _145_ (
    .A0(tx_data[5]),
    .A1(tx_shift_reg[5]),
    .S(_057_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _146_ (
    .A0(tx_data[6]),
    .A1(tx_shift_reg[6]),
    .S(_057_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(tx_data[7]),
    .A1(tx_shift_reg[7]),
    .S(_057_),
    .X(_023_)
  );
  sky130_fd_sc_hd__dfxtp_1 _148_ (
    .CLK(clk),
    .D(_000_),
    .Q(state[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _149_ (
    .CLK(clk),
    .D(_001_),
    .Q(state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _150_ (
    .CLK(clk),
    .D(_002_),
    .Q(state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _151_ (
    .CLK(clk),
    .D(_003_),
    .Q(tx_done_reg)
  );
  sky130_fd_sc_hd__dfxtp_1 _152_ (
    .CLK(clk),
    .D(_004_),
    .Q(bit_cnt[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _153_ (
    .CLK(clk),
    .D(_005_),
    .Q(bit_cnt[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _154_ (
    .CLK(clk),
    .D(_006_),
    .Q(bit_cnt[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _155_ (
    .CLK(clk),
    .D(_007_),
    .Q(tx_reg)
  );
  sky130_fd_sc_hd__dfxtp_1 _156_ (
    .CLK(clk),
    .D(_008_),
    .Q(baud_cnt[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _157_ (
    .CLK(clk),
    .D(_009_),
    .Q(baud_cnt[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _158_ (
    .CLK(clk),
    .D(_010_),
    .Q(baud_cnt[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _159_ (
    .CLK(clk),
    .D(_011_),
    .Q(baud_cnt[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _160_ (
    .CLK(clk),
    .D(_012_),
    .Q(baud_cnt[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _161_ (
    .CLK(clk),
    .D(_013_),
    .Q(baud_cnt[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _162_ (
    .CLK(clk),
    .D(_014_),
    .Q(baud_cnt[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _163_ (
    .CLK(clk),
    .D(_015_),
    .Q(baud_cnt[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _164_ (
    .CLK(clk),
    .D(_016_),
    .Q(tx_shift_reg[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _165_ (
    .CLK(clk),
    .D(_017_),
    .Q(tx_shift_reg[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _166_ (
    .CLK(clk),
    .D(_018_),
    .Q(tx_shift_reg[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _167_ (
    .CLK(clk),
    .D(_019_),
    .Q(tx_shift_reg[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _168_ (
    .CLK(clk),
    .D(_020_),
    .Q(tx_shift_reg[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _169_ (
    .CLK(clk),
    .D(_021_),
    .Q(tx_shift_reg[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _170_ (
    .CLK(clk),
    .D(_022_),
    .Q(tx_shift_reg[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _171_ (
    .CLK(clk),
    .D(_023_),
    .Q(tx_shift_reg[7])
  );
  assign tx = tx_reg;
  assign tx_done = tx_done_reg;
endmodule

module uart_top(clk, rx_pin, tx_pin, loopback_en, tx_start, tx_data, tx_done, rx_valid, rx_data);
  input clk;
  wire clk;
  wire internal_rx_pin;
  wire internal_tx_pin;
  input loopback_en;
  wire loopback_en;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  input rx_pin;
  wire rx_pin;
  output rx_valid;
  wire rx_valid;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output tx_done;
  wire tx_done;
  output tx_pin;
  wire tx_pin;
  input tx_start;
  wire tx_start;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(rx_pin),
    .A1(internal_tx_pin),
    .S(loopback_en),
    .X(internal_rx_pin)
  );
  \$paramod\uart_rx\CLKS_PER_BIT=s32'00000000000000000000000011011001  u_rx (
    .clk(clk),
    .rx(internal_rx_pin),
    .rx_data(rx_data),
    .rx_valid(rx_valid)
  );
  \$paramod\uart_tx\CLKS_PER_BIT=s32'00000000000000000000000011011001  u_tx (
    .clk(clk),
    .tx(internal_tx_pin),
    .tx_data(tx_data),
    .tx_done(tx_done),
    .tx_start(tx_start)
  );
  assign tx_pin = internal_tx_pin;
endmodule
